def channelCount(*args, **kwargs): pass
def channelNumber(*args, **kwargs): pass
def closeGraphEditor(*args, **kwargs): pass
def deselectAll(*args, **kwargs): pass
def focusEditor(*args, **kwargs): pass
def getChannelColor(*args, **kwargs): pass
def getChannelIndex(*args, **kwargs): pass
def getChannelMidiInPort(*args, **kwargs): pass
def getChannelName(*args, **kwargs): pass
def getChannelPan(*args, **kwargs): pass
def getChannelPitch(*args, **kwargs): pass
def getChannelVolume(*args, **kwargs): pass
def getCurrentStepParam(*args, **kwargs): pass
def getGridBit(*args, **kwargs): pass
def getGridBitWithLoop(*args, **kwargs): pass
def getRecEventId(*args, **kwargs): pass
def getStepParam(*args, **kwargs): pass
def getTargetFxTrack(*args, **kwargs): pass
def incEventValue(*args, **kwargs): pass
def isChannelMuted(*args, **kwargs): pass
def isChannelSelected(*args, **kwargs): pass
def isChannelSolo(*args, **kwargs): pass
def isGraphEditorVisible(*args, **kwargs): pass
def isGridBitAssigned(*args, **kwargs): pass
def isHighLighted(*args, **kwargs): pass
def midiNoteOn(*args, **kwargs): pass
def muteChannel(*args, **kwargs): pass
def processRECEvent(*args, **kwargs): pass
def selectAll(*args, **kwargs): pass
def selectChannel(*args, **kwargs): pass
def selectOneChannel(*args, **kwargs): pass
def selectedChannel(*args, **kwargs): pass
def setChannelColor(*args, **kwargs): pass
def setChannelName(*args, **kwargs): pass
def setChannelPan(*args, **kwargs): pass
def setChannelPitch(*args, **kwargs): pass
def setChannelVolume(*args, **kwargs): pass
def setGridBit(*args, **kwargs): pass
def setStepParameterByIndex(*args, **kwargs): pass
def showCSForm(*args, **kwargs): pass
def showEditor(*args, **kwargs): pass
def showGraphEditor(*args, **kwargs): pass
def soloChannel(*args, **kwargs): pass
def updateGraphEditor(*args, **kwargs): pass
version = 1.0
